server:
  port: 8080

spring:
  application:
    name: storacle-spring-boot-example

storacle:
  vendor: minio
  vendors:
    minio:
      endpoint: ${STORACLE_MINIO_ENDPOINT:http://192.168.50.152:9000}
      access-key: ${STORACLE_MINIO_ACCESS_KEY:admin}
      secret-key: ${STORACLE_MINIO_SECRET_KEY:password123}

